---
site_name: Trustworthy Platform Module (TwPM)
site_url: https://twpm.dasharo.com
repo_url: https://github.com/dasharo/twpm-docs
theme:
  name: material
  favicon: images/favicon.png
  logo: images/dasharo-logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
nav:
  - Intro:
      - index.md
  - Tutorials:
      - tutorials/index.md
      - Building TwPM: tutorials/building.md
  - Development:
      - development/index.md
      - Verilog modules: development/verilog_modules.md
  - Explanation:
      - explanation/index.md
      - Hardware requirements: explanation/hardware-requirements.md
      - Hardware selection: explanation/hardware-selection.md
      - Compliance: explanation/compliance.md
  - Changelog:
      - changelog/index.md
  - Contributing:
      - contributing/index.md
  - Roadmap:
      - roadmap/index.md
