---
site_name: Trustworthy Platform Module (TwPM)
site_url: https://twpm.dasharo.com
repo_url: https://github.com/dasharo/twpm-docs
theme:
  name: material
  favicon: images/favicon.png
  logo: images/dasharo-logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
nav:
  - 'Intro': index.md
  - 'Tutorials': tutorials/index.md
  - 'Development': development/index.md
  - 'Requirements': requirements/requirements.md
  - 'Explanation': explanation/index.md
  - 'Changelog': changelog/index.md
  - 'Contributing': contributing/index.md
  - 'Roadmap': roadmap/index.md
